import type { Metadata } from "next";
import "./globals.css";
import PaidPlanNudge from "./components/PaidPlanNudge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ background: "transparent" }}>
        <PaidPlanNudge />
        {children}
      </body>
    </html>
  );
}
